backend:
  name: git-gateway
  branch: main
  local_backend: true  # 启用本地开发模式，无需 Netlify 登录
  proxy_url: http://localhost:8081/api/v1  # 指向本地 decap-server

media_folder: 'src/assets/images'
public_folder: '/_astro'

collections:
  - name: 'post'
    label: 'Post'
    folder: 'src/data/post'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Excerpt', name: 'excerpt', widget: 'string', required: false }
      - { label: 'Category', name: 'category', widget: 'string', required: false }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          allow_add: true,
          allow_delete: true,
          collapsed: false,
          required: false,
          field: { label: 'Tag', name: 'tag', widget: 'string' },
        }
      - { label: 'Image', name: 'image', widget: 'string', required: false }
      - { label: 'Publish Date', name: 'publishDate', widget: 'datetime', required: false }
      - { label: 'Update Date', name: 'updateDate', widget: 'datetime', required: false }
      - { label: 'Author', name: 'author', widget: 'string', required: false }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false, required: false }
      - { label: 'Content', name: 'body', widget: 'markdown', required: true }
